### ISSUE TITLE
Job levels not being scraped correctly since Patch 5.2 release

### ISSUE THREAD

**Issue by jjmontalbo** [cleargelnotes/ffxiv-lodestone-parser-py#1]
Lodestone was updated with several backwards-incompatible changes to its HTML. Job levels are no longer being scraped correctly as a result.

Example: https://ffxiv.api.cleargelnotes.com/api/v0.1/latest?c=9197144

**Comment by cleargelnotes** [comment]
Fixed. Job data was moved to a new page in lodestone and this commit https://github.com/cleargelnotes/ffxiv-lodestone-parser-py/commit/14228ba36abf20f91c2df6eb86dd2c8fd16b54a2 should fix it
